import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Playfair_Display } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistPlayfairDisplay = Playfair_Display({
  variable: "--font-geist-playfair_display",
  subsets: ["latin"],
});

const geistOswald = Oswald({
  variable: "--font-geist-oswald",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${geistOswald.variable} ${geistPlayfairDisplay.variable} antialiased`}
        >
          <header className="flex justify-end items-center"></header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
